getmax <aertest.in
getmax <allsrcs.in1
getmax <allsrcs.in2
getmax <allsrcs.in3
getmax <allsrcs.in4
getmax <allsrcs.in5
getmax <allsrcs.in6
getmax <allsrcs.in7
getmax <capped.in1
getmax <capped.in2
getmax <capped.in3
getmax <capped.in4
getmax <capped.in5
getmax <capped.in6
getmax <capped.in7
getmax <capped.in8
getmax <capped.in9
getmax <capped_nostd.in1
getmax <capped_nostd.in2
getmax <capped_nostd.in3
getmax <capped_nostd.in4
getmax <testgas.in
getmax <testgas2.in
getmax <testpart.in
getmax <testprt2.in
getmax <openpits.in1
getmax <openpits.in2
getmax <openpits.in3
getmax <lovett.in
getmax <mcr.in
getmax <flatelev.in1
getmax <flatelev.in2
getmax <multurb.in1
getmax <multurb.in2
getmax <multurb.in3
getmax <multurb.in4
getmax <hrdow.in1
getmax <hrdow.in2
getmax <hrdow.in3
getmax <hrdow.in4
getmax <hrdow.in5
getmax <hrdow.in6
getmax <surfcoal.in1
getmax <surfcoal.in2
getmax <surfcoal.in3
getmax <surfcoal.in4
getmax <surfcoal.in5
getmax <surfcoal.in6
getmax <olm.in
getmax <olmgrp.in
getmax <pvmrm.in
getmax <psdcred.in1
getmax <psdcred.in2
getmax <scimtest.in1
getmax <scimtest.in2
getmax <scimtest.in3
getmax <scimtest.in4
getmax <scimtest.in5
getmax <scimtest.in6
getmax <testpm25.in
getmax <testpm10_1986.in
getmax <testpm10_1987.in
getmax <testpm10_1988.in
getmax <testpm10_1989.in
getmax <testpm10_1990.in
getmax <testpm10.in
copy aertest.sm+allsrcs.sm1+allsrcs.sm2+allsrcs.sm3+allsrcs.sm4+allsrcs.sm5+allsrcs.sm6+allsrcs.sm7+capped.sm1+capped.sm2+capped.sm3+capped.sm4+capped.sm5+capped.sm6+capped.sm7+capped.sm8+capped.sm9+capped_nostd.sm1+capped_nostd.sm2+capped_nostd.sm3+capped_nostd.sm4+testgas.sm+testgas2.sm+testpart.sm+testprt2.sm+openpits.sm1+openpits.sm2+openpits.sm3+lovett.sm+mcr.sm+flatelev.sm1+flatelev.sm2+multurb.sm1+multurb.sm2+multurb.sm3+multurb.sm4+hrdow.sm1+hrdow.sm2+hrdow.sm3+hrdow.sm4+hrdow.sm5+hrdow.sm6+surfcoal.sm1+surfcoal.sm2+surfcoal.sm3+surfcoal.sm4+surfcoal.sm5+surfcoal.sm6+olm.sm+olmgrp.sm+pvmrm.sm+psdcred.sm1+psdcred.sm2+scimtest.sm1+scimtest.sm2+scimtest.sm3+scimtest.sm4+scimtest.sm5+scimtest.sm6+testpm25.sm+testpm10_1986.sm+testpm10_1987.sm+testpm10_1988.sm+testpm10_1989.sm+testpm10_1990.sm+testpm10.sm aercmp_all.sum /b
